services:

  event-db:
    container_name: ewm-db
    image: postgres:16.1
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
  request-db:
    container_name: request-db
    image: postgres:16.1
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=request_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  comment-db:
    container_name: comment-db
    image: postgres:16.1
    restart: always
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=comment_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  user-db:
    container_name: user-db
    image: postgres:16.1
    restart: always
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
  stats-db:
    container_name: stats-db
    image: postgres:16.1
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345


  analyzer-db:
    container_name: analyzer-db
    image: postgres:16.1
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_DB=analyzer_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbuser
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 15
  kafka:
  image: confluentinc/confluent-local:7.4.3
  hostname: kafka
  container_name: kafka
  ports:
    - "9092:9092"
    - "9101:9101"
  restart: unless-stopped
  environment:
    KAFKA_NODE_ID: 1
    KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
    KAFKA_JMX_PORT: 9101
    KAFKA_JMX_HOSTNAME: localhost
    KAFKA_PROCESS_ROLES: 'broker,controller'
    KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
    KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
    CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: >
      bash -c '
        kafka-topics --create --topic stats.user-actions.v1
                     --partitions 1 --replication-factor 1 --if-not-exists
                     --bootstrap-server kafka:29092 &&
        kafka-topics --create --topic stats.events-similarity.v1
                     --partitions 1 --replication-factor 1 --if-not-exists
                     --bootstrap-server kafka:29092 &&
      '
    init: true